baseURL = 'https://ntqc.github.io/APATCC-11'
languageCode = 'en-us'
title = 'APATCC 11'
theme = 'universal'

[menu]
[[menu.main]]
name = "Home"
url = "/"

[[menu.main]]
name = "Program"
url = "/program/"

[[menu.main]]
name = "Venue"
url = "/venue/"
