baseURL = 'https://ntqc.github.io/APATCC-11'
languageCode = 'en-us'
title = 'APATCC 11'
theme = 'universal'

[menu]
[[menu.main]]
name = "Home"
url = "/"
#weight = 1

[[menu.main]]
name = "Program"
url = "/program/"
#weight = 2

[[menu.main]]
name = "Registration"
url = "/registration/"
#weight = 3

[[menu.main]]
name = "Venue"
url = "/venue/"
#weight = 4

[[menu.main]]
name = "Comittee"
url = "/comittee/"
#weight = 4

# [params]
# copyright = "comittee"

[params.about]
enable = true
title = "About"
subtitle = "subt"
